user:
  name: Thami Sadouk
  email: thami.sadouk@gmail.com
  timezone: UTC

preferences:
  skills:
    - golang
    - software engineer
  salaryMinimum: 80000
  location: Remote

#hardNos:
#  - family
